apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: privoro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privoro
  template:
    metadata:
      labels:
        app: privoro
    spec:
      containers:
      - name: privoro-app
        image: gcr.io/privoro-264120/privoro:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
